### ISSUE TITLE
rename the package

### ISSUE THREAD

**Issue by schochastics** [GESIS-Methods-Hub/andrew#115]
@yfiua @chainsawriot @rgaiacs @arnim 
We probably need to semantically separate the package from the actual Methods Hub Portal a bit, given that it can be used for other Websites too. The package is the CMS that powers such websites.  Lets gather some suggestion and try come to a decision for the 1.0.0 milestone.   Something that reminds of CMS with a touch of open source/open science/reproducibility

**Comment by schochastics** [comment]
- git2web

**Comment by chainsawriot** [comment]
[rahm](https://www.duden.de/rechtschreibung/Rahm) - Reproducibilty-Aware *Hubs Maker

**Comment by rgaiacs** [comment]
I would like to call it `andrew` in reference to [Robin Williams](https://en.wikipedia.org/wiki/Robin_Williams) character in [Bicentennial Man](https://en.wikipedia.org/wiki/Bicentennial_Man_(film)). In the movie, NDR series robot "Andrew" goes on a journey to become human. Our content have their own journey to be reproducible.

**Comment by yfiua** [comment]
I would say we pick a "searchable" term so that when people google it not some random thing pops up.

**Comment by schochastics** [comment]
andrew: **A**ggregator for **N**avigatable **D**iscoverable  **R**eproducible and  **E**ducational **w**ork

**Comment by schochastics** [comment]
@rgaiacs I think we can settle for this name if you are ok with it

**Comment by rgaiacs** [comment]
Looks good to me. I will make the changes.
