### ISSUE TITLE
Content Management System (CMS) vs Content Aggregation System

### ISSUE THREAD

**Issue by rgaiacs** [GESIS-Methods-Hub/andrew#117]
@schochastics at the moment, `methodshub` is more like a content aggregation system than a content management system.

# Content Aggregation/Syndication System

- [ ] Collect third-party content

# Content Curation System

- [ ] Organise, arrange, and present third-party content

# Content Management System

- [ ] Add content
- [ ] Modify content
- [ ] Remove content

**Comment by schochastics** [comment]
That is a good point. We should frame it like that then. Any negative consequences?
We need to think about the management part though. Is this the "Submission form" then?

**Comment by rgaiacs** [comment]
> Any negative consequences?

Not that I can think of.

> We need to think about the management part though. Is this the "Submission form" then?

The management part at the moment is a very hack CSV file. The submission form is part of the management system that should also include modify and remove.

**Comment by schochastics** [comment]
I guess what is holding us back from a less hacky version is the clarification of classification of content?
Say that is "solved", Do you already have some nonhacky solutions  in mind?

**Comment by schochastics** [comment]
Sounds good. You can put that on your own roadmap as you please. The only requirement from my side is to keep in mind that the classification might be very fluid :)
