### ISSUE TITLE
Review updated "Input Format" documentation

### ISSUE THREAD

**Issue by rgaiacs** [GESIS-Methods-Hub/andrew#123]
I updated https://gesis-methods-hub.github.io/methodshub/articles/input-format.html.

@schochastics I included formats that we hope to support and link to the respective issue.

@arnim Did I forgot any MyST related format?

@yfiua I included a note covering Python packages. Is that sufficient?

**Comment by yfiua** [comment]
great, thanks!

**Comment by arnim** [comment]
Maybe it's also worth collecting some community feedback. For Jupyter this could be at [discourse](https://discourse.jupyter.org). There are also some [interesting posts](https://discourse.jupyter.org/t/feature-idea-jupyterhub-binderhub-jupyter-book-as-a-publishing-platform/8359) on this subject 😄

**Comment by yfiua** [comment]
could just set up a discord though for rapid feedback

**Comment by chainsawriot** [comment]
How about this for [this file](https://github.com/GESIS-Methods-Hub/methodshub/blob/main/vignettes/input-format.Rmd) 

```md

# Supported formats

## README.md

## Markdown

....

# Unsupported formats (yet)

## Quarto (book)

...

```

If you think that this organization is better, I can submit a PR.

**Comment by schochastics** [comment]
@chainsawriot I like this organization
