### ISSUE TITLE
Support Quarto's Callout Blocks

### ISSUE THREAD

**Issue by rgaiacs** [GESIS-Methods-Hub/andrew#149]
Consider

```
---
title: "MWE"
author: Raniere Silva
---

Foo

::: {.callout-important}

This is important!

:::
```

We are using `quarto render mwe.md --from markdown --to markdown --output mwe.md-output` that produces

```
---
author:
- Raniere Silva
title: MWE
toc-title: Table of contents
---

Foo

<div>

> **Important**
>
> This is important!

</div>
```

Which is render by Quarto as

![Screenshot 2023-07-25 at 13-36-57 Demo of MethodsHub - Minimal Example of Tutorial in Quarto Markdown](https://github.com/GESIS-Methods-Hub/andrew/assets/1506457/1299b04e-8de7-4aa6-92e7-ce1b75674e7b)

**Comment by juliandehne** [comment]
@rgaiacs I am not sure this counts as unsupported. It produces acceptable output. Should we close it as wontfix?

**Comment by rgaiacs** [comment]
> Should we close it as wontfix?

Yes, it can be close.
