### ISSUE TITLE
read in CITATION.cff

### ISSUE THREAD

**Issue by juliandehne** [GESIS-Methods-Hub/andrew#220]
- [ ] read in CFF files in the repository automatically and display them in cite section

**Comment by 1234Mannheim** [comment]
Danke. Bitte noch den unterstrich in KODAQS Toolbox raus und oben auf der Seite noch üver scalearch bitte sowas schreiben wie "Cite as: .xxxxx" . Danke Jessica

**Comment by juliandehne** [comment]
Es gibt oben den Cite Button, der jetzt aber kaputt gegangen ist.

**Comment by juliandehne** [comment]
der Unterstrich ist raus, und der Cite-Befehl in Menu oben ist repariert. Über dem Titel noch was einfügen geht gegen das Standard-Quarto Layout und auch nach HTML-Prinzip sollte Titel das erste Element sein. Der Cite-Button sollte die Funktion erfüllen. Sonst kann der Block mit dem Cite_as auch in den Tools individuell nach oben geschoben werden.
