### ISSUE TITLE
Size of tutorial images

### ISSUE THREAD

**Issue by annestroppe** [GESIS-Methods-Hub/andrew#223]
Based on the metadata information (e.g., minimal-example-qmd-rstats-units), tutorial images should be 900×600 pixels but in the running version images of the size (e.g. tool 'Assessment of Uncertain Geospatial Linking, img size 898x601 pixel) is cropped. Could you update if we need to adjust the size or is there another reason?

**Comment by rgaiacs** [comment]
The tutorial image cover recommendation to be 900x600 is because of space in the user screen and to improve performance of the portal.

The tutorial can have images in the body of any size.

**Comment by annestroppe** [comment]
Thanks, Raniere! Do you have any tips on what size we should choose so that the images are not cut off?

**Comment by rgaiacs** [comment]
Dear @annestroppe, can you provide a screenshot of the problem that you are having?

@juliandehne This might be able to be solve by changing the CSS.

**Comment by juliandehne** [comment]
Sorry, I missed the conversation. It is a technical issue and I am working on it. This is an examplary issue report. We should use this, if further issues arise.

**Comment by juliandehne** [comment]
Fixed with commit 1b600696fc8408720b8e3720db41296c756e39fb
