### ISSUE TITLE
Footer changes

### ISSUE THREAD

**Issue by juliandehne** [GESIS-Methods-Hub/andrew#230]
- KODAQS Logo GESIS , Uni Mannheim und LMU Logos, sowie funded by BMBF und EU einfügen. Leibniz Gemeinschaft kann , wenn es Platzprobleme gibt, raus 

- „Datenschutz“ sieht durch die andere Schriftart und den fehlenden Abstand zum Leibniz Logo fehl am Platz aus. Vorschlag: Nach links oder rechts verschieben in die spalte neben das Leibniz Logo (bzw neben anderelogos wenn ausgewechselt)  

- s.o. ‚License‘ aus dem Header in den Footer verschieben, am besten zum Datenschutz. Wir haben uns noch gefragt: Brauchen wir kein Impressum? Wurde das mit der Kommunikation geklärt? 

- Social Media Links führen nur auf die social media main page und haben alle nen weißen Rand. Vorschlag: Verlinkung der KODAQS Seiten, weil wir die user ja auf unsere Seiten lenken wollen

**Comment by juliandehne** [comment]
Der aktuelle Footer versucht, den GESIS-Footer nachzuahmen. Bitte mit David klären, ob es ok ist, von dem GESIS-Design komplett wegzugehen. 

Ein Wireframe für den neuen Design für den Footer wäre gut, damit ich das nachbauen kann. So ist es mir unklar.

**Comment by juliandehne** [comment]
![image](https://github.com/user-attachments/assets/c5f9cf56-01d5-4000-80b7-9377f4c22694)
could look like this.

**Comment by juliandehne** [comment]
"Bitte KODAQS Kompetenzzentrum DQ…. Ins Impressum und die GESIS Adressen der beidne Standorte raus   "

**Comment by juliandehne** [comment]
> ![image](https://private-user-images.githubusercontent.com/22906595/385838838-c5f9cf56-01d5-4000-80b7-9377f4c22694.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NzMxOTksIm5iZiI6MTczMTU3Mjg5OSwicGF0aCI6Ii8yMjkwNjU5NS8zODU4Mzg4MzgtYzVmOWNmNTYtMDFkNS00MDAwLTgwYjctOTM3N2Y0YzIyNjk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDA4MjgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0OGExYzQ4NTM1Mzc0MjljNmZjMTMzN2M3YWVkMTcwZGM2NDdjOWE4OTIzMWY0ZTQwN2U1ZDYwMmM3MTg5YTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Y_TYFHloWWCfzByOgP7HnR5fgSfwNd-DhNPohI_TaMc) could look like this.

Is da noch ein Menu im Footer?

**Comment by juliandehne** [comment]
Der Vorschlag von Anne ist ein guter Startpunkt, aber da sind zwei Navigationsstrukturen drin bei Themen und unten nochmal. Quarto-Footer haben immer drei Bereiche. Ich würde zwei Zeilen nehmen, die blaue mit dem Kontakt linker Bereich, mittlerer Bereich vllt. Gesis Kontakt und rechter dann so wie bei dem aktuellen mit GESIS-Logo und Link zu dem Impressum. Gerne in dem Issue-Thread antworten.

**Comment by annestroppe** [comment]
Sounds good to me!

**Comment by juliandehne** [comment]
![image](https://github.com/user-attachments/assets/5a7dc47a-bffa-431b-bbe5-3db9f7c2bdba)

Der Vorschlag von Anne für die leiste über dem Footer

**Comment by juliandehne** [comment]
GESIS-Theme oder das? Oder beides versuchen mit den Logos über dem Footer?
